### ISSUE TITLE
GPIO.cleanup cleans more than it should

### ISSUE THREAD

**Issue by paulgerman94** [alaudet/hcsr04sensor#13]
The library itself handles setting the GPIO mode, pin initialization and at the end it calls GPIO.cleanup on the 2 pins.

this last cleanup, for some reason, deletes any callback I had set on ANY other input pins (callback set using GPIO.add_event_detect)
I'm guessing this is a GPIO bug by itself. Took me 2 days to figure it out...

The issue in my opinion with the library is that it shouldn't handle at all setting the GPIO mode and even setting up/cleaning the pins. These should be done by the user before using the library because it has a global impact, not only in the library.

Any thoughts?

**Comment by alaudet** [comment]
Interesting.  This was something that was contributed from another user
because the module was explicitly clobbering other pins that were in
use for other purposes.  Entering that line fixed it for him.

I added setting of the mode and cleanup to make it easier for people and
not have to do it in their code.  The module is pretty straightforward
in that it should clean up those two pins only.  Have you tried removing
that functionality and just handling it with your own
code?  Does it work that way?

If I change it, it will break some user applications.

What version or RPi.GPIO are you using?

**Comment by alcalyn** [comment]
Also, are you sure you need to do:

``` python
GPIO.setwarnings(False)
GPIO.setmode(self.gpio_mode)
```

? First it does it every time we trigger a measure, and it also create a side effect.

I think the module should not be responsible of that. This code should be run in our own source code.

**Comment by paulgerman94** [comment]
@alaudet I have the last GPIO version (0.6.3). And yes, once I remove the pin cleaup in the library, it works - the callback remains active. I don't understand how the 2 pins remaining active could clobber other pins.
@alcalyn I agree

**Comment by alaudet** [comment]
Hey guys, I haven't forgotten about this, I just have not had any time at all the past couple of months to deal with anything.  You make good points and hope I can spend some time on this in the future.  I am always open to making changes suggested by others.

**Comment by alaudet** [comment]
Hey guys, again, my apologies for letting this slide.  Too much stuff going on in life right now.  I am sure you already have your own workarounds but your points are well taken.  While it works for some the way it is, it obviously causes a problem in some situations.  I think I will add a second script called sensor_basic.py that simply does a basic reading and lets you handle all of the other things you would rather do in your own code.  That way I am not breaking anything else out there and new projects do not have to put up with design decisions that don't work for them.

All sensor_basic would do is return a reading in cm's, no cleanups...etc etc.  your thoughts appreciated.

**Comment by alaudet** [comment]
Added a stand alone function called basic_distance to sensor.py that will allow handling of everything in your own code.  Been added to devel branch only right now.  Will merge to master in near future.

**Comment by alaudet** [comment]
Version 1.5.3 adds basic_distance function to the sensor which gives you full control over the following;
GPIO.setmode
GPIO.setwarnings
GPIO.cleanup

See https://github.com/alaudet/hcsr04sensor/blob/master/recipes/basic_reading.py for example
