### ISSUE TITLE
dropout invalid distance

### ISSUE THREAD

**Issue by december-soul** [alaudet/hcsr04sensor#18]
Hello

I have a suggestion on how to improve the accuracy a bit more.
I have a setup in which only distances from 1cm to 200cm can occur.
I would therefore like to discard all values over 200cm.
Although the average value is already calculated over the 11 measurements, these 11 measurements may contain "invalid" values.
If these are filtered out before the mean value is calculated, the mean value will also be more accurate.
Therefore, an additional parameter would be nice.

You could solve it like this (untested):
```
def raw_distance(self, sample_size=11, sample_wait=0.1, dropout_min=Integer.MIN_VALUE, dropout_max=Integer.MAX_VALUE):
```
...
```
            if distance_cm >= dropout_min and distance_cm <= dropout_max:
                sample.append(distance_cm)
```
But be careful, it could be that all values are then filtered out. The sample array would then be empty.

Considering that you have a sorted_sample list and use the // operator, the accuracy will only improve slightly.

**Comment by alaudet** [comment]
Hi thanks for the suggestion.  Currently the median reading variance is one cm.  How much of an improvement can this provide since all readings have small variances.

**Comment by alaudet** [comment]
I am always open to new ideas.  If it is something you want to pursue, then submit a pull request.  Make sure that unittests pass and that your pull request is off the devel branch. 

Also some extra information on how you tested this and expand on some of the issues you mention in your post.  I can already think of some problems and given the nature of the hcsr04 I am currently satisified with the variance and highly doubt it will make much difference.  The sensor itself is the limitation.  If you can prove that variance of readings is reduced (i.e. actually improves readings) then lets look at it.

 I will close the issue for now.
