### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by andrew-j-turner** [alaudet/hcsr04sensor#5]
When taking a measurement the program ended up in an infinite loop waiting for the GPIO pin to go high.

This problem is solved by putting a for loop around the GPIO pin readings.

**Comment by alaudet** [comment]
I am not following.  I am not sure how an infinite loop can happen here unless you took a very large sample size.  Can you provide more information on your method of taking a reading?

A traceback when you kill the loop would be helpful.

**Comment by alaudet** [comment]
I am unable to reproduce this error on python2 or 3. If you could provide more info it would be appreciated.

**Comment by alaudet** [comment]
I have not heard back from the submitter and I cannot reproduce the error.  I am closing the issue and will re-open it if the error can be reproduced.

**Comment by alaudet** [comment]
This error has been replicated when dealing with a faulty sensor or cable.  I will look to address it in the next devel release and have opened a seperate tracker for it.
