### ISSUE TITLE
sonar_signal_off referenced before assignment

### ISSUE THREAD

**Issue by milandicic** [alaudet/hcsr04sensor#8]
I'm getting error "UnboundLocalError: local variable 'sonar_signal_off' referenced before assignment'"

That happens usually when object is out of rage after few valid readings a get this error and script stop working...

screenshot - http://prntscr.com/bh1ysq

**Comment by alaudet** [comment]
Oh wow, your last readings are like 100 feet which is way further than the sensor is even capable of.  What are you trying to do exactly? 

I have seen this when I set sample_wait too low.
The default values are as follows;

value.raw_distance(sample_size=11, sample_wait=0.1)

Did you increase the speed of the wait time between readings?

I have seen it when setting sample_wait lower than 0.1. which pretty much causes it to initiate another reading before its processed the return of the first sample reading.
If you don't need extremely fast readings you can try setting it to 0.3 for example.

**Comment by milandicic** [comment]
Yeah I know. That false readings happend when sensor signal don't bounce from a flat surface for example when nothing is in front of the sensor so it can't receive echo signal i suppose.

I'm trying to develop a script which will detect when someone stands in front of the sensor and than to play video on two RPi-s at the same time synchronously. I attached sensor on one Pi and connect that Pi to another one and after object detection "master" will send signal to "slave" and both will play video at the same time...

I managed to just skip this false readings and error with try and catch, when error happen I just catch it and then continue with script just like that error didn't ocure...

Also i didn't change sample_wait time. 

(I hope you understand sorry for  my english :) )

**Comment by alaudet** [comment]
I understand perfectly.  I really should add error handling for this type of thing.  It seems that you have found a workaround.  I think I am going to add something to catch the Unbound Errors and return a little more sane information than just a traceback like this.  Now to just implement it properly.
