### ISSUE TITLE
CPU Loop

### ISSUE THREAD

**Issue by babberk** [alaudet/hcsr04sensor#9]
About every two weeks my Pi goes into a loop in the program running the hcsr04sensor code.  The distance measurement runs every 60 seconds and does 7 readings each time.  I believe it is looping while waiting for the GPIO pin to go high as Andrew J Turner stated.  I suspect something occurs in the OS to delay the program and by the time it gets back, the high signal is gone.  It would be helpful to have a loop iteration check during the while GPIO.input(self.echo_pin) == 0: to bail out of the while loop after some period of time.

**Comment by alaudet** [comment]
Are you able to catch a stack trace of the error on your console?  It would be helpful to understand what you are measuring, the distances involved and to see your code as well.

I have seen some issues when the reading is too far as there is a limit to the distance the sensor can read.

**Comment by babberk** [comment]
I'm not much of a Linux expert, so I'll have to research how to catch a stack trace.  The program is rather simple and is attached.  It is measuring the water level in a sump pit.  Distance is 3 to 6 feet.  The only thing that can loop in the program is the while statement in hcsr04sensor.  The CPU goes to 100% and stays there in the water level program.

**Comment by alaudet** [comment]
Usually if you just let the program run in a console if it throws an error it will print out the error.
I also use this for a sump pump but my distances are smaller than yours are.  You could try adjusting the parameters to slow the readings down a little. 

Example

value = sensor.Measurement(TRIG, ECHO)
distance = value.raw_distance(sample_wait=0.3)

The default sample_wait is 0.1 which may be a little quick.  For a sump pump you don't need extremely quick readings so you could even try setting it to 0.5 .

Of course without seeing your code or seeing what the error is I am only guessing that this may be the issue.

**Comment by babberk** [comment]
There is no error thrown.  It just goes into a 100% CPU loop.  I change the sample wait time as you recommend and we'll see what happens.  I don't see how that will affect where the loop occurs though.  Please consider a for loop instead of while when waiting for the GPIO echo pin to go high.  Thanks.   My code is

def main():

```
ReadingCount=0

while True:
    trig_pin = 17
    echo_pin = 27

    # Default values
    # unit = 'metric'
    # temperature = 20
    # round_to = 1

    # Create a distance reading with the hcsr04 sensor module
    # and overide the default values for temp, unit and rounding)


    value = sensor.Measurement(trig_pin,
                              echo_pin,
                              temperature=66,
                              unit='imperial',
                              round_to=1
                               )
    # sample wait set to .3 on 10/9/16
    raw_measurement = value.raw_distance(sample_size=7, sample_wait=0.3)

    # Calculate the distance in inches
    imperial_distance = value.distance_imperial(raw_measurement)/12

    if imperial_distance<50 and imperial_distance>0:
        conn=sqlite3.connect(dbname)
        curs=conn.cursor()

        curs.execute("""INSERT INTO waterlevel values(datetime('now'), (?))""", (imperial_distance,))

        conn.commit()
        conn.close()

    # print("The Distance = {} feet".format(imperial_distance))

    if imperial_distance<1:
        ReadingCount=ReadingCount+1
    else:
        ReadingCount=1
    if imperial_distance<2 and ReadingCount>=5:
        sendemailalert('Water Level Alert',imperial_distance,ReadingCount)
        ReadingCount=(-10)

    time.sleep(60)
```

if **name** == "**main**":
    main()

**Comment by alaudet** [comment]
This is difficult for me to troubleshoot with the information you are providing.  If your script is hung and your cpu is at 100% you could Crtl-Break the script to see where in the code it is hung up.

I have never seen this issue reported with anyone else so I cannot even be sure the hcsr04sensor module is the issue.  There is no way for me to reproduce your issue.  I have done extensive testing on the module issuing large sample sizes and I can never get the CPU to go higher than 7%.
The while loop is just listening for a condition and when it detects it does an action. 

I agree that the sample_wait may not help now that you state the program is not exiting with an error.  It usually does when the readings are being done too quickly for the application it is being used for.  But I did not know that your program was still running but just maxing at 100%.

You are welcome to try and modify the source of hcsr04sensor to see if you can address your issue.

Even if I did it, I would not know what I am fixing and if it even worked.  There are quite a few others using the module and I have not had this issue reported and introducing a change without understanding what I am fixing could be asking for trouble.

If you change the code and are able to fix your issue I would be interested in seeing how you did so I can learn from it.

**Comment by babberk** [comment]
It went into a loop today.  The traceback was:
File "monitorwatertest.py", line 79, in main
  raw_measurement = value.raw_distance(sample_size=11, sample_wait=0.1)
File "/usr/local/lib/python2.7/dist-packages/hcsr04sensor/sensor.py", line 83, in raw_distance
  sonar_signal_off = time.time()

It never saw the echo pin go high.  I will set up a counter to break out of the while loop after awhile (pun intended).  We'll see what happens.

**Comment by alaudet** [comment]
ok thanks.  I have been trying to make it hang with various tests and am not able to.  My own sump monitor has been running since July 2014 and it has been solid.  1440 readings per day for over two years.   I would like to see what you did to fix your issue.

**Comment by babberk** [comment]
Here is what I did:

for distance_reading in range(sample_size):
            loopcounter = 1
            GPIO.output(self.trig_pin, GPIO.LOW)
            time.sleep(sample_wait)
            GPIO.output(self.trig_pin, True)
            time.sleep(0.00001)
            GPIO.output(self.trig_pin, False)

```
        while GPIO.input(self.echo_pin) == 0 and loopcounter <1000:
            loopcounter = loopcounter +1
        sonar_signal_off = time.time()   
        while GPIO.input(self.echo_pin) == 1:
            pass
        sonar_signal_on = time.time()
        if loopcounter >=1000:
            time_passed = 0
        else:
            time_passed = sonar_signal_on - sonar_signal_off 
        distance_cm = time_passed * ((speed_of_sound * 100) / 2)
        sample.append(distance_cm)
```

I did some testing and found that depending on the CPU load, the first while loop iterates about 60 times.  Occasionally, it would only do 30 or 40 iterations.  The lowest I saw in brief testing was 11 iterations.  Interestingly, the second while loop iterates about 1700 times for a 7.2 ms echo (about 4 feet). 

I also moved the sonar_signal = time.time() statements to outside the while loops.  I get more iterations (100 to 150) on the first while loop.  The distance calculation doesn't seem to be affected.  Just seems a little more efficient to me that way.

I'll let this run for a few weeks and we'll see what happens.  I should never get in a loop now.

**Comment by alaudet** [comment]
Thanks for sharing this.  I will look at this closer when I get a bit of time.   Please let me know if it fixes the problem.  Are you finding that it goes into these continuous loops on longer readings only or it doesn't really matter the distance?

**Comment by alaudet** [comment]
I was able to reproduce the issue today.  I have a sump pit that I monitor and I noticed that it stopped taking readings yesterday for the first time in almost two and half years.  When I went into the console I could see that my process for my sump monitor was stuck at 100% CPU.  When I broke from the program it was exactly the same error message that you got.  It was stuck in what seemed like an infinite loop.

When I checked the sensor I could see a bit of rust on the pins, so I put a new sensor on it.  When I put the cable on it I could hear crunching like there was rust inside the connector.  Still went into an inifinite loop.  

I pulled the pi off the wall and set it up with a new sensor on a breadboard and now it is working fine.

Could it be that you have a faulty sensor or cable.  It makes sense that you would get stuck in an infinite loop if the sensor was not reporting back for whatever reason.  It just kind of sits there waiting.

**Comment by alaudet** [comment]
At this point I think what I will do is similar to what you have done here with the loop, but instead of setting the time_passed = 0 I will will make it throw an  exception and log it to an error_file.  A faulty wire or sensor will cause this and it is better to raise an exception then to give a faulty reading which, by setting time_passed to 0 will give an erroneous measurement (0 cm's) and play havoc with anyone graphing results.

I would rather my script exit and give me an explanation of why and possible causes then just have it hanging at 100% cpu usage indefinitely or providing an erroneous reading.  When I have time I will throw this into the devel branch and test it thoroughly.
